# Generated by Django 2.0.7 on 2022-06-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Task Label',
                'verbose_name_plural': 'Task Labels',
                'db_table': 'task_label',
            },
        ),
    ]
